info:
  name: delete_role
  type: http
  seq: 4

http:
  method: DELETE
  url: "{{apiUrl}}/org-admin/roles/c13e3750-1c08-4109-af41-0e6df9103c94"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
